version: 1.1.{build}
image: Visual Studio 2022
install:
  - dotnet tool install -g dotnet-reqube
  - dotnet tool install -g Cake.Tool --version 3.0.0
  - dotnet tool install -g coverlet.console --version 3.2.0
  - SET JAVA_HOME=C:\Program Files\Java\jdk17
  - SET PATH=%JAVA_HOME%\bin;%PATH%
build_script:
- cmd: dotnet cake --Target=CI
test: off
cache:
  - tools
  - '%USERPROFILE%\.sonar\cache'
