version: 1.1.{build}
image: Visual Studio 2022
install:
  - dotnet tool install -g dotnet-reqube
  - dotnet tool install -g Cake.Tool --version 0.36.0
  - dotnet tool install -g coverlet.console --version 1.7.0
build_script:
- cmd: dotnet cake -Target=CI
test: off
cache:
  - tools
  - '%USERPROFILE%\.sonar\cache'
